@startuml
start;
if(search by name?) then(yes);
:search by family name;
       if(familyName exists) then(yes)
            :listAllMembersByFamilyName;
            :input member info by Name and first name;
            :getMemberByNameAndFirstName(name,first);
            :return member;
            stop;
        else(no)
        :return "Does not exist";
        stop;
        endif;
else(no);
 :search by memberID;
 :input memberID;
 if(memberID exists) then(yes)
 :getMemberbyID(iDnumber);
 :return member;
 stop
 else(no)
 :return error;
 end
 endif;









@enduml