@startuml

start
:Librarian provides memberID;

if (Member ID does not exist) then (yes)
    :error message;
    end;
else (no)
    : Print all Member information;
    :Choose information to update:
    - Name
    - Date of Birth
    - Fines;

    :Update selected information;
    stop

@enduml