@startuml

start
   : Admin Provides Add Method;
if (book is fiction) then (yes)
    :set bookIdNo;
    :add book;
    end;

elseif (book is non fiction) then (yes)
    :set bookIdNo;
    :add book;
    end;

elseif(book is children) then (yes)
    :set bookIdNo;
    :add book;
    end;

else (no  Others )
    :set bookIdNo;
    :add book;
    end;
endif


@enduml

@startuml




Admin --> bookApp : input book info


BookApp --> BookService : addAnimal(Animal n,newAnimal)
AnimalService --> AnimalRepository : getAnimal()
AnimalService <-- AnimalRepository : List<Animal>

alt New Animal already exist In the List
AnimalService --> AnimalShelterApp : return false
user <-- AnimalShelterApp : Sorry Animal already present

else Add new animal in the list
AnimalService --> AnimalService : aanroep add method of list to add new animal
AnimalShelterApp <-- AnimalService : return true
user <-- AnimalShelterApp : animal added

end
@enduml

